In [21]:
import torch



In [23]:
x = torch.tensor([1,2,3], dtype=torch.float32, requires_grad=True)  # requires grad = true means pytorch will track all operations on this tensor
print(x)

tensor([1., 2., 3.], requires_grad=True)


In [24]:
y = 2*x+2
print(y)

tensor([4., 6., 8.], grad_fn=<AddBackward0>)


In [25]:
z = x*x*2
print(z)

tensor([ 2.,  8., 18.], grad_fn=<MulBackward0>)


In [26]:
z = z.mean()
print(z)

tensor(9.3333, grad_fn=<MeanBackward0>)


In [27]:
z.backward()
print(x.grad)    # dz/dxi for all xi in x

tensor([1.3333, 2.6667, 4.0000])


In [30]:
# if z is not a scalar (i.e. a single value) then u need to provide a gradient argument of the same size as z 
# which acts like the d(Loss)/d(z) term 
# d(Loss)/dx1 = d(Loss)/dZ . dZ/d(x1)

gradient = torch.tensor([1,1,1], dtype=torch.float32)
z = x*x*2
z

tensor([ 2.,  8., 18.], grad_fn=<MulBackward0>)

In [31]:
z.backward(gradient)
print(x.grad)

tensor([ 5.3333, 10.6667, 16.0000])
