In [2]:
import torch
import numpy as np

In [2]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.4725,  0.2638,  1.3996,  0.3762],
        [ 2.0941, -0.9447,  0.6608, -2.6446],
        [ 1.0755,  1.3078, -0.5678, -1.2693]])

In [3]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
arr = np.array([1, 2, 3, 4, 5])
linspacearray = np.linspace(0,10,4)
print(linspacearray)
print(arr)



[ 0.          3.33333333  6.66666667 10.        ]
[1 2 3 4 5]


In [7]:
print(arr.dtype)
print(arr.shape)



int32
(5,)


In [8]:
#convert np array to tensor
mytensor = torch.tensor(arr)
mytensor


tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [15]:
#reshaping row,column
tensor2 = torch.tensor([1,2,3,4,5,6])
tensor2.reshape(2,3)
tensor3 = tensor2.reshape(2,-1)   #rows = 2 and columns accordingly
print(tensor2)
print(tensor3)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [16]:
#grabbing a specific item
var = tensor2[3]
var

tensor(4)

In [17]:
#grabbing a slice
rangevar = tensor2[3:]
rangevar

tensor([4, 5, 6])

In [20]:
#returns 1 column as a tensor
tensor3[:,1]

tensor([1, 4])

In [4]:
tensor4 = torch.tensor([1,2,3,4])
tensor5 = torch.tensor([3,5,1,8])
torch.add(tensor4,tensor5)

tensor([ 4,  7,  4, 12])

In [7]:
torch.sub(tensor4,tensor5)

tensor([-2, -3,  2, -4])

In [8]:
tensor4 % tensor5  # torch.remainder()

tensor([1, 2, 0, 4])

In [9]:
torch.pow(tensor4,tensor5)

tensor([    1,    32,     3, 65536])

In [13]:
#add in the same vector

tensor4 = tensor4.add(tensor5)
tensor4



tensor([ 4,  7,  4, 12])