In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

# basically download the MNIST data set from kaggle digit recognizer.

data = pd.read_csv(r'C:\Users\prith\Downloads\archive (1)\mnist_train.csv')

In [3]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]              
X_train = X_train / 255.
_,m_train = X_train.shape

In [12]:
X_train.shape

(784, 59000)

In [5]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5                   # produce small values in the range [-0.5,0.5)
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)                           # basic relu # cant write max(0,z) cause it is just for scalar inputs. np.maximum is defined for vector inputs or matrix inputs as well.

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))                     # basic softmax
    return A                                           # here z is a vector or a matrix

In [6]:
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0                                  # returns 1 when x>0 ad 0 when x<=0 so acts as a derivative of ReLU

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1                    # converts into one hot encoding of labels
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

In [7]:
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)                         # mathematically calculated derivatives
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2                              # update the weights basic gradient descent
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [8]:
def get_predictions(A2):
    return np.argmax(A2, 0)                                  # returns the predictions colummn wise 

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size                 # returns accuracy as decimal

In [9]:
def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [10]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[0 0 0 ... 0 0 0] [3 9 6 ... 6 6 5]
0.10091525423728813
Iteration:  10
[8 8 6 ... 6 3 7] [3 9 6 ... 6 6 5]
0.19698305084745762
Iteration:  20
[8 8 6 ... 6 3 7] [3 9 6 ... 6 6 5]
0.27315254237288134
Iteration:  30
[3 8 6 ... 6 3 7] [3 9 6 ... 6 6 5]
0.33915254237288134
Iteration:  40
[3 8 6 ... 6 3 5] [3 9 6 ... 6 6 5]
0.4010169491525424
Iteration:  50
[3 8 6 ... 6 3 5] [3 9 6 ... 6 6 5]
0.4665084745762712
Iteration:  60
[3 9 6 ... 6 3 5] [3 9 6 ... 6 6 5]
0.5253050847457628
Iteration:  70
[3 9 6 ... 6 3 5] [3 9 6 ... 6 6 5]
0.5770508474576271
Iteration:  80
[3 9 6 ... 6 3 5] [3 9 6 ... 6 6 5]
0.6174406779661017
Iteration:  90
[3 9 6 ... 6 3 5] [3 9 6 ... 6 6 5]
0.6494406779661017
Iteration:  100
[3 9 6 ... 6 3 5] [3 9 6 ... 6 6 5]
0.6757457627118644
Iteration:  110
[3 9 6 ... 6 3 5] [3 9 6 ... 6 6 5]
0.6973389830508474
Iteration:  120
[3 9 6 ... 6 6 5] [3 9 6 ... 6 6 5]
0.7162372881355932
Iteration:  130
[3 9 6 ... 6 6 5] [3 9 6 ... 6 6 5]
0.7315593220338983
Iteration:  1